# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: torchmind/circleci-openjdk:9-jdk-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - store_test_results:
          path: target/surefire-reports
      - run: |
          mkdir /tmp/artifacts/
          cp target/org.basinmc.lavatory-*.jar /tmp/artifacts/
          cp -r target/apidocs/ /tmp/artifacts/
          cp -r target/surefire-reports/ /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts/
          destination: /
